- name: "deploy setenv.sh"
  template: src=setenv.j2 dest=/usr/local/apache-tomcat-8.0.23/bin/setenv.sh owner=root group=root

- name: "Deploy startup script"
  template: src=tomcat.service.j2 dest=/etc/systemd/system/tomcat.service owner=root mode=777
