#---------------Ansible EC2 Creation----------------
---
- name: Create a new Demo EC2 instance
  hosts: localhost
  gather_facts: False

  vars:
      region: ap-south-1
      instance_type: t2.micro
      ami: ami-5b673c34  #Redhat
      keypair: aws-latest # pem file name

  tasks:

    - name: Create an ec2 instance
      ec2:
         key_name: "{{ keypair }}"
         aws_access_key: "{{ my_access_key }}"
         aws_secret_key: "{{ my_secret_key }}"
         group: launch-wizard-2  # security group name
         instance_type: "{{ instance_type }}"
         image: "{{ ami }}"
         wait: true
         region: "{{ region }}"
         count: 2  # default
         count_tag:
            Name: "Ansible_Demo_ec2"
         instance_tags:
            Name: "Demo_Ansible"
         vpc_subnet_id: "subnet-b5b13ff9"
         assign_public_ip: yes
      register: ec2
    
    - name: Debugging  EC2 creation
      debug: var=ec2
#boto required
